SELECT H.HACKER_ID,H.NAME,SUM(TEMP.MSCORE) AS SSCORE
FROM HACKERS H JOIN (SELECT S.HACKER_ID,MAX(SCORE) AS MSCORE FROM SUBMISSIONS S GROUP BY S.HACKER_ID,S.CHALLENGE_ID) AS TEMP
ON H.HACKER_ID=TEMP.HACKER_ID
GROUP BY H.HACKER_ID,H.NAME
HAVING SSCORE>0
ORDER BY SSCORE DESC, H.HACKER_ID
