SELECT ROUND(AVG(LAT_N),4) AS MEDIAN
FROM (
    SELECT LAT_N, ROW_NUMBER() OVER (ORDER BY LAT_N) ROW_NUM,
    COUNT(*) OVER() TOTAL_COUNT FROM STATION
)
NUMBERED_ROWS WHERE ROW_NUM IN ((TOTAL_COUNT+1)/2,(TOTAL_COUNT+2)/2);