SELECT      
    C.COMPANY_CODE,
    C.FOUNDER,
    COUNT(DISTINCT LM.LEAD_MANAGER_CODE) AS NUM_LEAD_MANAGERS,
    COUNT(DISTINCT SM.SENIOR_MANAGER_CODE) AS NUM_SENIOR_MANAGERS,
    COUNT(DISTINCT M.MANAGER_CODE) AS NUM_MANAGERS,
    COUNT(DISTINCT E.EMPLOYEE_CODE) AS NUM_EMPLOYEES
FROM 
    COMPANY C
    JOIN LEAD_MANAGER LM ON C.COMPANY_CODE = LM.COMPANY_CODE
    JOIN SENIOR_MANAGER SM ON LM.LEAD_MANAGER_CODE = SM.LEAD_MANAGER_CODE
    JOIN MANAGER M ON SM.SENIOR_MANAGER_CODE = M.SENIOR_MANAGER_CODE
    JOIN EMPLOYEE E ON M.MANAGER_CODE = E.MANAGER_CODE
GROUP BY 
    C.COMPANY_CODE, 
    C.FOUNDER
ORDER BY 
    C.COMPANY_CODE;
